# Generated by Django 2.1.1 on 2018-11-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=256)),
                ('usr_lastname', models.CharField(max_length=256)),
                ('usr_phone', models.CharField(max_length=256)),
                ('usr_email', models.CharField(max_length=256)),
                ('usr_address', models.CharField(max_length=256)),
                ('usr_city', models.CharField(max_length=256)),
                ('usr_state', models.CharField(max_length=256)),
                ('usr_dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='UsersTypes',
            fields=[
                ('uty_id', models.AutoField(primary_key=True, serialize=False)),
                ('uty_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='usr_uty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.UsersTypes'),
        ),
    ]
