# Generated by Django 2.1.1 on 2018-11-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('tkp_id', models.AutoField(primary_key=True, serialize=False)),
                ('tkp_description', models.TextField(max_length=1000)),
                ('tkp_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tsk_id', models.AutoField(primary_key=True, serialize=False)),
                ('tsk_name', models.CharField(max_length=256)),
                ('tsk_createDate', models.DateTimeField(auto_now_add=True)),
                ('tsk_targetDate', models.DateTimeField()),
                ('tsk_finishDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('tck_id', models.AutoField(primary_key=True, serialize=False)),
                ('tck_name', models.CharField(max_length=256)),
                ('tck_description', models.TextField(max_length=1000)),
                ('tck_createDate', models.DateTimeField(auto_now_add=True)),
                ('tck_startDate', models.DateTimeField()),
                ('tck_targetDate', models.DateTimeField()),
                ('tck_finishDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
