# Generated by Django 2.1.1 on 2018-11-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('tkp_id', models.AutoField(primary_key=True, serialize=False)),
                ('tkp_description', models.TextField(max_length=1000)),
                ('tkp_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tsk_id', models.AutoField(primary_key=True, serialize=False)),
                ('tsk_name', models.CharField(max_length=256)),
                ('tsk_createDate', models.DateTimeField(auto_now_add=True)),
                ('tsk_targetDate', models.DateTimeField()),
                ('tsk_finishDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('tck_id', models.AutoField(primary_key=True, serialize=False)),
                ('tck_name', models.CharField(max_length=256)),
                ('tck_description', models.TextField(max_length=1000)),
                ('tck_createDate', models.DateTimeField(auto_now_add=True)),
                ('tck_startDate', models.DateTimeField()),
                ('tck_targetDate', models.DateTimeField()),
                ('tck_finishDate', models.DateTimeField(auto_now=True)),
                ('tck_usr_inCharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='tsk_tck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.Tickets'),
        ),
        migrations.AddField(
            model_name='progress',
            name='tkp_tck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.Tickets'),
        ),
    ]
