# Generated by Django 2.1.1 on 2018-11-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='tck_usr_inCharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='tsk_tck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.Tickets'),
        ),
        migrations.AddField(
            model_name='progress',
            name='tkp_tck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.Tickets'),
        ),
    ]
