# Generated by Django 2.1.1 on 2018-11-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('cmp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmp_name', models.CharField(max_length=256)),
                ('cmp_address', models.CharField(max_length=256)),
                ('cmp_city', models.CharField(max_length=256)),
                ('cmp_state', models.CharField(max_length=256)),
                ('cmp_postalCode', models.CharField(max_length=256)),
                ('cmp_phone', models.CharField(max_length=14)),
                ('cmp_email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('cpc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpc_departament', models.CharField(max_length=256)),
                ('cpc_name', models.CharField(max_length=256)),
                ('cpc_email', models.CharField(max_length=256)),
                ('cpc_phone', models.CharField(max_length=256)),
                ('cpc_cmp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Companies.Companies')),
            ],
        ),
    ]
